### PR TITLE
Feat printmap pj

### PR DESCRIPTION
**Pull request by JohnerPierre**
Ajoute l'impression de la Map

Pour le moment cela imprime la carte avec le titre et la date de création en texte et en braille.

La conversion en braille est fait grâce au module "braille" de npm .

L'impression de la carte se fait grâce à un service (printMap.service.ts).

### CODE REVIEW

**Comment by jcavat** [comment]
It would be better to create a component instead of a function which returns an html-string.

**Comment by JohnerPierre** [comment]
Ok , i work on it and i update the code

**Comment by jcavat** [comment]
Maybe you should use 
`window.open('some_url')` 
somewhere and manage the route of your component in the app-routing.module.ts file

**Comment by JohnerPierre** [comment]
I have add a route for print the map , It remains two bugs , I am in the process of settling them

1. Share varaible between the route (map,title,..)
2. Auto print when the page is up

**Comment by jcavat** [comment]
Ok. Please, rename PrintMap.component.ts to print-map.component.ts to be consistent with our naming convention. The same for printMap.service.ts to print-map.service.ts. Rename also print.css to print-map.component.css and use styleUrls in the Component decorator to link it. Create print-map.component.html instead of defining it on the Component decorator (templateUrl). Take a look on the other components. Thanks

**Comment by jcavat** [comment]
I'm available at my office if you have any questions

**Comment by jcavat** [comment]
It seems impossible to share service between navigator tabs.

**Comment by jcavat** [comment]
We will push into the master branch your first version which stays functional. Restart from commit 8f6e507 and create a new branch from it : 
```
git checkout 8f6e507
git checkout -b feat-printmap-v2
```
Then, improve the template with the same padding and enlarge it. Finaly, pull request the branch. I close this one.
Thanks

**Pull request closed without merging**
