### PR TITLE
Feat localisation pj

### PR DESCRIPTION
**Pull request by JohnerPierre**

### CODE REVIEW

**Comment by JohnerPierre** [comment]
Add Localisation for the project.

It remains two problems
- #88  & #87 

And add the italian language

**Comment by jcavat** [comment]
Did you pull the master branch on yours ? It seems not.

**Comment by JohnerPierre** [comment]
Done

**Comment by JohnerPierre** [comment]
Merge done working on #87

**Comment by JohnerPierre** [comment]
I don't know why travis failed.
https://gyazo.com/fe1d820db82dca00159da5b1773d4b9f
In my computer npm test work

**Comment by jcavat** [comment]
Did you fix it ? In case of problem, remove `node_modules` locally and run `npm install` again.

**Comment by JohnerPierre** [comment]
Localy it's work fine but half of travis' test semms to not work in GitHub

**Comment by jcavat** [comment]
Did you remove `node_modules` locally ?

**Comment by JohnerPierre** [comment]
Yes and it still works

**Comment by jcavat** [comment]
I ran the test process again on Travis and it works. Do the same if it occurs one more times.

**Comment by JohnerPierre** [comment]
Ok thanks for the help

**Comment by JohnerPierre** [comment]
Add comments for "hack"

**Pull request merged**
